# Tensorflow 설치

In [ ]:
!pip install -U tensorflow
# colab은 이미 설치되어 있으므로 필요 없음

In [1]:
import tensorflow as tf
print('Tensorflow versio :', tf.__version__)

Tensorflow versio : 2.13.0


## 텐서와 연산

In [3]:
# 스칼라 tensor 를 생성

tensor1 = tf.constant(21)
print(tensor1)

# 배열을 가지고 tensor 를 생성

tensor2 = tf.constant([[1, 2], [4, 6]])
print(tensor2)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(
[[1 2]
 [4 6]], shape=(2, 2), dtype=int32)


In [ ]:
# tensor 의 인덱싱

# 행은 전체, 열은 0번 이후 위치
print(tensor2[:, 0:])
# 첫번째 열만 선택해서 1차원 배열로 생성
print(tensor2[:, 0])
# 첫번째 열만 선택하고 다차원 배열로 생성
print(tensor2[:, 0, tf.newaxis])
# tf.newaxis 를 추가하면 차원이 하나 추가됨

tf.Tensor(
[[1 2]
 [4 6]], shape=(2, 2), dtype=int32)
tf.Tensor([1 4], shape=(2,), dtype=int32)
tf.Tensor(
[[1]
 [4]], shape=(2, 1), dtype=int32)


In [ ]:
# tensor의 연산

print(tensor1 + 10)
print(tensor2 + 10) # 배열과 broadcast 연산 수행
print(tf.square(tensor2)) # 제곱 연산
print(tensor2 @ tf.transpose(tensor2)) # 행렬의 곱

tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(
[[11 12]
 [14 16]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 1  4]
 [16 36]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 16]
 [16 52]], shape=(2, 2), dtype=int32)


In [4]:
from tensorflow import keras
K = keras.backend
K.square(K.transpose(tensor2)) + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 46]], dtype=int32)>

In [5]:
import numpy as np
ar = np.array([1, 2, 3,4 ])

# numpy 의 데이터로 tensor 를 생성
data = tf.constant(ar)
print(data)

# tensor 를 numpy 배열로 변경
numpy_data = data.numpy()
print(numpy_data)
print(type(numpy_data))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)
[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# numpy 와 tensor 의 연산에 데이터의 공유가 가능

# tensorflow 연산에 numpy 를 사용할 수 있고 반대도 마찬가지
print(tf.square(ar))
print(np.square(data))

tf.Tensor([ 1  4  9 16], shape=(4,), dtype=int64)
[ 1  4  9 16]


In [ ]:
# 자료형이 달라서 에러가 발생

try:
    # int 와 float 사이에 자료형이 달라서 연산이 불가능
    x = tf.constant(10) + tf.constant(3.14)
except tf.errors.InvalidArgumentError as ex:
    print(ex)

cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2] name: 


In [ ]:
try:
    # int 와 float 사이에 자료형이 달라서 연산이 불가능
    #x = tf.constant(10) + tf.constant(3.14)
    print(tf.cast(tf.constant(10), tf.float32) + tf.constant(3.2))
except tf.errors.InvalidArgumentError as ex:
    print(ex)

tf.Tensor(13.2, shape=(), dtype=float32)


In [ ]:
# Variable 을 이용해서 변수 생성
var = tf.Variable([[1, 2], [3, 4]])
print(var)
# assign 을 사용해서 데이터 변경
var.assign(var + 5)
print(var)
# 특정 위치만 데이터 변경
var[0, 0].assign(10)
print(var)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[6, 7],
       [8, 9]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 8,  9]], dtype=int32)>


## 문자열 Tensor

In [6]:
# 문자열 tensor
# shape 를 갖지 않으며 encoding 된 상태로 저장
# 기본 자료형
tf.constant('오늘의 날씨')

<tf.Tensor: shape=(), dtype=string, numpy=b'\xec\x98\xa4\xeb\x8a\x98\xec\x9d\x98 \xeb\x82\xa0\xec\x94\xa8'>

In [11]:
# TensorArray - 텐서의 배열

# 데이터의 타입과 크기를 지정해야 함
array = tf.TensorArray(dtype = tf.float32, size = 5)
print(array)

# write 함수를 이용해서 데이터를 생성하고 수정
array = array.write(0, tf.constant(1.0))
array = array.write(1, tf.constant(3.2))
array = array.write(0, tf.constant(1.5))

# array 의 데이터를 읽을 때는 read 함수에 인덱스를 사용해야 함
print(array.read(0)) # 1.5

tf.Tensor(1.5, shape=(), dtype=float32)


In [13]:
# Ragged Tensor
# 각 배열의 길이가 달라도 되지만 자료형은 같아야 함

ar = tf.ragged.constant([[1], [2, 3], [4, 5, 6]])
print(ar)

<tf.RaggedTensor [[1], [2, 3], [4, 5, 6]]>


In [18]:
# sparse tensor

# 3행 4열의 행렬을 만들고
# indices 로 지정한 위치에 values 의 데이터를 순서대로 배정
# dense_shape 를 통해 행렬을 저장할 dense matrix 를 지정
sp = tf.SparseTensor(indices = [[0, 1], [1, 1], [1, 3], [2, 2]],
                     values = [1.0, 1.5, 3.2, 4.5],
                     dense_shape = [3, 4])

# to_dense 함수를 이용해서 sparse matrix인 데이터를 밀집 행렬로 표현
print(tf.sparse.to_dense(sp))


tf.Tensor(
[[0.  1.  0.  0. ]
 [0.  1.5 0.  3.2]
 [0.  0.  4.5 0. ]], shape=(3, 4), dtype=float32)


In [22]:
# set

set1 = tf.constant([[1, 2, 3, 2], [2, 3, 1, 4]])
set2 = tf.constant([[1, 2, 3, 3], [2, 4, 1, 5]])

# set 연산을 수행하면 희소 행렬 형태가 되므로
# to_dense 를 사용해서 표현
tf.sparse.to_dense(tf.sets.union(set1, set2))
# set 연산을 수행하면 중복을 제거
# 배열의 모양을 일치시키기 위해 0을 추가

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 2, 3, 0, 0],
       [1, 2, 3, 4, 5]], dtype=int32)>

In [23]:
# 데이터 노드 생성
node1 = tf.constant(2.3)
node2 = tf.constant(3.5)

# 그래프 실행
print(node1, node2)

tf.Tensor(2.3, shape=(), dtype=float32) tf.Tensor(3.5, shape=(), dtype=float32)


In [28]:
# 텐서플로우 코드 최적화가 가능하도록 작성

# 최적화를 위해 @tf.function 를 사용
# 결과는 동일하지만 중간 과정이 달라짐
# tensor 로 변환해서 연산을 수행하기 때문
@tf.function
def tf_cube(data):
  # 값의 변화가 없는 구문이므로 함수 호출 전에 전부 수행해버림
  print(data)
  # 텐서플로우 함수 호출 구문으로 변경되어서 실행
  return data ** 3

result = tf_cube(tf.constant(3.0))
print(result)

# 파이썬의 함수는 호출할 때 처리를 하지만
# tensorflow 는 먼저 읽어서 최적화를 한 다음에 함수가 호출되면 필요한 부분을 처리

Tensor("data:0", shape=(), dtype=float32)
tf.Tensor(27.0, shape=(), dtype=float32)


In [33]:
# 데이터를 랜덤하게 생성

# 0 ~ 1 사이에서 랜덤하게 5개 데이터를 균등한 분포로
rand = tf.random.uniform([5], 0, 1)
print(rand)

# 0 ~ 1 사이에서 랜덤하게 2행 5열 데이터를 균등한 분포로
rand2 = tf.random.uniform([2, 5], 0, 1)
print(rand2)

# 5개의 난수 발생
# 평균은 3.0, 표준편차는 1.0인 정규 분포에서
nor = tf.random.normal([5], 3.0, 1.0)
print(nor)

tf.Tensor([0.6357156  0.20514452 0.72203195 0.70116436 0.6194576 ], shape=(5,), dtype=float32)
tf.Tensor(
[[0.24477446 0.8708143  0.5907656  0.68229437 0.9608811 ]
 [0.4198494  0.9484148  0.79188514 0.7595192  0.82257223]], shape=(2, 5), dtype=float32)
tf.Tensor([3.3826137 3.859873  2.2647958 3.6272798 3.666954 ], shape=(5,), dtype=float32)


## 뉴런 생성

In [34]:
# 활성화 함수 - sigmoid 함수
import math

def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [35]:
# 입력 값
X = 1.0
# target
y = 0.0

# 가중치를 랜덤하게 설정
w = tf.random.normal([1], 0, 1)

# 출력
output = sigmoid(X * w)
print('예측 값 :', output)

예측 값 : 0.6822630501300433


In [37]:
# 경사 하강법

# 1000 이 epoch
for i in range(1000):
  output = sigmoid(X * w)
  error = y - output
  # 학습률을 0.1로 설정
  w = w + X * 0.1 * error

  # 50번마다 확인
  if i % 50 == 0:
    print(i, output, error)


0 0.6822630501300433 -0.6822630501300433
50 0.22202505140591564 -0.22202505140591564
100 0.11436079872008159 -0.11436079872008159
150 0.07517414845173018 -0.07517414845173018
200 0.05557258437327877 -0.05557258437327877
250 0.043938436448071064 -0.043938436448071064
300 0.03627261743919787 -0.03627261743919787
350 0.030854936027550586 -0.030854936027550586
400 0.02682925019310826 -0.02682925019310826
450 0.02372329695823802 -0.02372329695823802
500 0.021255887099897668 -0.021255887099897668
550 0.01924946224045666 -0.01924946224045666
600 0.017586453726033374 -0.017586453726033374
650 0.016186021438326523 -0.016186021438326523
700 0.01499080382387332 -0.01499080382387332
750 0.013958906322268441 -0.013958906322268441
800 0.01305918259969475 -0.01305918259969475
850 0.012267785191445505 -0.012267785191445505
900 0.01156634553369373 -0.01156634553369373
950 0.01094041788180252 -0.01094041788180252


In [41]:
# 경사 하강법에 문제 발생 - X 가 0이라 가중치가 변하지 않음
# 가중치만 사용하는 경우 input 이 0이면 가중치가 변하지 않는게 문제점

X = 0
y = 1
w = tf.random.normal([1], 0, 1)

for i in range(1000):
  output = sigmoid(X * w)
  error = y - output
  # X 에 에러를 곱해서 가중치를 수정하는데
  # X 가 0이므로 가중치가 변할 수 없음
  w = w + X * 0.1 * error

  if i % 50 == 0:
    print(i, output, error)

0 0.5 0.5
50 0.5 0.5
100 0.5 0.5
150 0.5 0.5
200 0.5 0.5
250 0.5 0.5
300 0.5 0.5
350 0.5 0.5
400 0.5 0.5
450 0.5 0.5
500 0.5 0.5
550 0.5 0.5
600 0.5 0.5
650 0.5 0.5
700 0.5 0.5
750 0.5 0.5
800 0.5 0.5
850 0.5 0.5
900 0.5 0.5
950 0.5 0.5


In [42]:
# 경사 하강법에 편향을 추가해서 문제 해결
# input이 0이어도 학습을 수행

X = 0
y = 1
w = tf.random.normal([1], 0, 1)
# 편향 설정
b = tf.random.normal([1], 0, 1)

for i in range(1000):
  output = sigmoid(X * w + b)
  error = y - output
  w = w + X * 0.1 * error
  # bias 도 0으로 설정될 수 있으므로 지속적으로 수정 해줌
  b = b + 1 * 0.1 * error

  if i % 50 == 0:
    print(i, output, error)

0 0.7656764142643964 0.23432358573560363
50 0.8820002812341016 0.11799971876589843
100 0.9232009404664779 0.07679905953352206
150 0.9435258484038097 0.05647415159619029
200 0.9554930225465634 0.04450697745343657
250 0.9633377931745115 0.036662206825488486
300 0.9688620967888664 0.031137903211133633
350 0.9729562041768853 0.02704379582311467
400 0.976108590327815 0.02389140967218495
450 0.9786089238305713 0.021391076169428702
500 0.9806395299707651 0.01936047002923491
550 0.9823208145274276 0.017679185472572412
600 0.9837353233711496 0.01626467662885045
650 0.9849417138157364 0.015058286184263636
700 0.9859825208921306 0.014017479107869435
750 0.9868895794150685 0.013110420584931504
800 0.9876869661881429 0.01231303381185711
850 0.9883934026068276 0.01160659739317238
900 0.9890235499728324 0.010976450027167628
950 0.989589112003287 0.01041088799671297


In [44]:
print(error)

0.009910221026367072


In [50]:
# AND 를 뉴런으로 구현
# 입력과 출력만 수정하면 OR 도 구현 가능

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [0], [0], [1]])
b = tf.random.normal([1], 0, 1)
# 이번에는 입력이 2개이므로 가중치도 2개가 되어야 함
w = tf.random.normal([2], 0, 1)

for i in range(2000):
  # 오차의 합계
  error_sum = 0

  # 모든 입력을 대입해서 수행해야 하므로 4번
  for j in range(4):
    output = sigmoid(np.sum(X[j] * w) + 1*b)
    error = y[j][0] - output
    w = w + X[j] * 0.1 * error
    b = b + 1 * 0.1 * error
    error_sum += error

  if i % 100 == 0:
    print(i, error_sum)

0 0.07970691932493523
100 -0.14740814537086844
200 -0.10073737112094117
300 -0.07689759667553142
400 -0.062172473428068475
500 -0.05212933470514142
600 -0.04483701561368156
700 -0.03930499866354886
800 -0.03496682421700348
900 -0.03147670894317525
1000 -0.028609472612023554
1100 -0.02621317681733898
1200 -0.024182178066849996
1300 -0.022438334046988945
1400 -0.020926112623579296
1500 -0.019602010901439232
1600 -0.018433545029231294
1700 -0.01739552083443162
1800 -0.0164667672877669
1900 -0.01563088813083885


In [51]:
# 모델을 fit(훈련) 한 결과를 가지고 predict
# 00, 01, 10 일 때는 0, 11 일 때는 1 의 근사치가 나와야 함

for i in range(4):
  print('X :', X[i], 'y :', y[i])
  print('Predict :', sigmoid(np.sum(X[i]*w) + b))

X : [0 0] y : [0]
Predict : 2.3002669486883006e-05
X : [0 1] y : [0]
Predict : 0.024760307553547273
X : [1 0] y : [0]
Predict : 0.024835052972201455
X : [1 1] y : [1]
Predict : 0.965646214710535


In [52]:
# OR 을 경사 하강법을 통해 구현
# 나머지는 AND 와 동일하고 입력과 출력(X 와 y) 부분만 수정

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])
b = tf.random.normal([1], 0, 1)
w = tf.random.normal([2], 0, 1)

# 훈련 과정
for i in range(2000):
  error_sum = 0

  for j in range(4):
    output = sigmoid(np.sum(X[j] * w) + 1*b)
    error = y[j][0] - output
    w = w + X[j] * 0.1 * error
    b = b + 1 * 0.1 * error
    error_sum += error

  if i % 100 == 0:
    print(i, error_sum)

0 1.9336685099540443
100 -0.10113886914842624
200 -0.05308038832763559
300 -0.035804659921112064
400 -0.026916209252407147
500 -0.02150826690360029
600 -0.017879826513691646
700 -0.0152819848585454
800 -0.01333289313483875
900 -0.011818388533519922
1000 -0.01060875510619598
1100 -0.009620835499703731
1200 -0.008799100275134655
1300 -0.008105435800825421
1400 -0.007511991614363209
1500 -0.006998710482600576
1600 -0.006550184606683995
1700 -0.0061551757279530855
1800 -0.0058052318805129795
1900 -0.005491855659200753


In [53]:
# OR 에 대해 predict

for i in range(4):
  print('X :', X[i], 'y :', y[i])
  print('Predict :', sigmoid(np.sum(X[i]*w) + b))

X : [0 0] y : [0]
Predict : 0.025842973381606706
X : [0 1] y : [1]
Predict : 0.9897146796369729
X : [1 0] y : [1]
Predict : 0.9896975504060317
X : [1 1] y : [1]
Predict : 0.9999971301601164


In [55]:
# 뉴런을 1개 사용해서 XOR 을 구현

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])
b = tf.random.normal([1], 0, 1)
w = tf.random.normal([2], 0, 1)

# 훈련 과정
for i in range(2001):
  error_sum = 0

  for j in range(4):
    output = sigmoid(np.sum(X[j] * w) + 1*b)
    error = y[j][0] - output
    w = w + X[j] * 0.1 * error
    b = b + 1 * 0.1 * error
    error_sum += error

  if i % 100 == 0:
    print(i, error_sum)

for i in range(4):
  print('X :', X[i], 'y :', y[i])
  print('Predict :', sigmoid(np.sum(X[i]*w) + b))

0 1.3462333773965582
100 -0.0008646440273877287
200 -0.00017449620217013795
300 -3.5197400656605815e-05
400 -7.0854904141715025e-06
500 -1.4286403157148797e-06
600 -2.9875806850654385e-07
700 -3.8159131521275924e-08
800 -6.980329025907395e-08
900 -6.980329025907395e-08
1000 -6.980329025907395e-08
1100 -6.980329025907395e-08
1200 -6.980329025907395e-08
1300 -6.980329025907395e-08
1400 -6.980329025907395e-08
1500 -6.980329025907395e-08
1600 -6.980329025907395e-08
1700 -6.980329025907395e-08
1800 -6.980329025907395e-08
1900 -6.980329025907395e-08
2000 -6.980329025907395e-08
X : [0 0] y : [0]
Predict : 0.5128177040587629
X : [0 1] y : [1]
Predict : 0.5000000363215804
X : [1 0] y : [1]
Predict : 0.48718236853665897
X : [1 1] y : [0]
Predict : 0.4743815336379531


In [57]:
# 값이 너무 작아서 input 을 제대로 반영하지 못함
print('W :', w)
print('Bias :', b)

W : tf.Tensor([-0.10256381 -0.05128191], shape=(2,), dtype=float32)
Bias : tf.Tensor([0.05128205], shape=(1,), dtype=float32)


In [ ]:
# 여러 개의 뉴런을 사용해서 XOR 을 구현

# 가중치와 편향은 따로 지정하지 않음
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

# 여러 layer 를 쌓는 모델을 제공
# unit 은 각 layer 에 사용하는 뉴런의 갯수
# 활성 함수는 activation 으로 지정
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units = 2, activation = 'sigmoid',
                          input_shape = (2, )),
    tf.keras.layers.Dense(units = 1, activation = 'sigmoid')
])

# 모델은 컴파일이 필요
# SGD(경사 하강법)를 사용하고 loss 함수로 mse 를 사용
model.compile(optimizer = tf.keras.optimizers.SGD(lr = 0.1), loss = 'mse')

model.summary()

# 모델 훈련
history = model.fit(X, y, epochs = 2000, batch_size = 1)

# 예측
model.predict(X)


# 2000번 반복 결과 - loss 가 0.2993 에서 0.2491 로 감소
# 2000번 반복으로는 결과가 이전과 별 차이가 없음
'''
array([[0.46576068],
       [0.5146458 ],
       [0.49633583],
       [0.5363298 ]], dtype=float32)
'''